version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: chat_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chat_db
    volumes:
      - ./db/dump:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chat_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  website:
    build: ./website
    container_name: website
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=chat_db
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
    restart: always

  chat:
    build: ./chat
    container_name: chat
    networks:
      - app_network
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - app_network
    depends_on:
      - website
      - chat
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  dump: