# Используем официальный образ Python
FROM python:3.10

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта
COPY . .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Запускаем WebSocket-сервер
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
